// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calc_R2_colsums_rcpp
NumericVector calc_R2_colsums_rcpp(NumericMatrix X);
RcppExport SEXP _flashier_calc_R2_colsums_rcpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_R2_colsums_rcpp(X));
    return rcpp_result_gen;
END_RCPP
}
// calc_R2_rowsums_rcpp
NumericVector calc_R2_rowsums_rcpp(NumericMatrix X);
RcppExport SEXP _flashier_calc_R2_rowsums_rcpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_R2_rowsums_rcpp(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flashier_calc_R2_colsums_rcpp", (DL_FUNC) &_flashier_calc_R2_colsums_rcpp, 1},
    {"_flashier_calc_R2_rowsums_rcpp", (DL_FUNC) &_flashier_calc_R2_rowsums_rcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_flashier(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
