# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_R2_colsums_rcpp <- function(X) {
    .Call('_flashier_calc_R2_colsums_rcpp', PACKAGE = 'flashier', X)
}

calc_R2_rowsums_rcpp <- function(X) {
    .Call('_flashier_calc_R2_rowsums_rcpp', PACKAGE = 'flashier', X)
}

